@Library('mylibrary')_

pipeline
{
    agent any
    stages
    {
        stage('Download')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('Build')
        {
            steps
            {
                script
                {
                    cicd.buildartifact()
                }
            }
        }
        stage('Deployment')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("Sharedlibrary","172.31.10.172","testapp")
                }
            }
        }
        stage('Testing')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("FunctionalTesting")
                    cicd.runSelenium("Sharedlibrary")
                }
            }
        }
        stage('Delivery')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("Sharedlibrary","172.31.3.113","myprod")
                }
            }
        }
    }
}

